name: auto-deploy-gatway
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 拉取代码
      uses: actions/checkout@v2
    - name: 准备jdk8 环境
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: 打包后端
      run: mvn -B -Dmaven.test.skip=true package --file pom.xml
    - name: 构建网关镜像
      run: docker build -f ./ruoyi-gateway/Dockerfile -t ${{ secrets.DOCKER_REPOSITORY }}/ruoyi-gateway:latest ./ruoyi-gateway
    - name: 构建服务镜像
      run: docker build -f ./ruoyi-modules/ruoyi-system/Dockerfile -t ${{ secrets.DOCKER_REPOSITORY }}/ruoyi-system:latest ./ruoyi-modules/ruoyi-system
    - name: 登录到阿里云镜像
      run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
    - name: 推送网关镜像
      run: docker push ${{ secrets.DOCKER_REPOSITORY }}/ruoyi-gateway:latest
    - name: 推送微服务镜像
      run: docker push ${{ secrets.DOCKER_REPOSITORY }}/ruoyi-system:latest      
  pull-docker:
    needs: [build]
    name: Pull Docker
    runs-on: ubuntu-latest
    steps:
      - name: 部署后端
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          port: ${{ secrets.HOST_PORT }}
          script: |
            docker stop $(docker ps --filter ancestor=${{ secrets.DOCKER_REPOSITORY }}/ruoyi-gateway -q)
            docker rm -f $(docker ps -a --filter ancestor=${{ secrets.DOCKER_REPOSITORY }}/ruoyi-gateway:latest -q)
            docker rmi -f $(docker images ${{ secrets.DOCKER_REPOSITORY }}/ruoyi-gateway:latest -q)
            docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
            docker pull ${{ secrets.DOCKER_REPOSITORY }}/ruoyi-gateway:latest
            docker run -d --name ruoyi-gateway -p 8080:8080 ${{ secrets.DOCKER_REPOSITORY }}/ruoyi-gateway:latest
            docker stop $(docker ps --filter ancestor=${{ secrets.DOCKER_REPOSITORY }}/ruoyi-system -q)
            docker rm -f $(docker ps -a --filter ancestor=${{ secrets.DOCKER_REPOSITORY }}/ruoyi-system:latest -q)
            docker rmi -f $(docker images ${{ secrets.DOCKER_REPOSITORY }}/ruoyi-system:latest -q)
            docker pull ${{ secrets.DOCKER_REPOSITORY }}/ruoyi-system:latest
            docker run -d --name ruoyi-system -p 9201:9201 ${{ secrets.DOCKER_REPOSITORY }}/ruoyi-system:latest