name: Vue-Test-CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 拉取代码
      uses: actions/checkout@v2
    - name: 准备Node.js环境
      uses: actions/setup-node@v1
      with:
        node-version: 8
    - name: 打包前端
      run: |
        npm install --prefix ./ruoyi-ui
        npm run --prefix ./ruoyi-ui build:prod 
    - name: 构建镜像
      run: docker build -f ./ruoyi-ui/Dockerfile -t ${{ secrets.DOCKER_REPOSITORY }}ruoyi-ui:latest ./ruoyi-ui
    - name: 登录到阿里云镜像
      run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
    - name: 推送镜像
      run: docker push ${{ secrets.DOCKER_REPOSITORY }}ruoyi-ui:latest
  pull-docker:
    needs: [build]
    name: Pull Docker
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          port: ${{ secrets.HOST_PORT }}
          script: |
            docker stop $(docker ps --filter ancestor=${{ secrets.DOCKER_REPOSITORY }}ruoyi-ui -q)
            docker rm -f $(docker ps -a --filter ancestor=${{ secrets.DOCKER_REPOSITORY }}ruoyi-ui:latest -q)
            docker rmi -f $(docker images ${{ secrets.DOCKER_REPOSITORY }}ruoyi-ui:latest -q)
            docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
            docker pull ${{ secrets.DOCKER_REPOSITORY }}:latest
            docker run -d -p 8000:80 ${{ secrets.DOCKER_REPOSITORY }}ruoyi-ui:latest